const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const clubs = [
  // ===== 原有12个 =====
  {
    name: "代码创想社",
    category: "学术科技",
    description: "专注于编程技术学习与项目实践，定期举办黑客马拉松、算法竞赛和技术分享会。无论你是编程新手还是技术大牛，都能在这里找到志同道合的伙伴。",
    tags: JSON.stringify(["编程", "算法", "人工智能", "Web开发", "技术"]),
    logo: "💻",
    contactInfo: "QQ群：123456789 | 微信公众号：代码创想",
    memberCount: 156,
    requirements: "对编程有兴趣即可，不限专业和基础",
  },
  {
    name: "星辰摄影协会",
    category: "文体艺术",
    description: "用镜头捕捉校园之美，组织外拍采风、摄影展览和后期修图教学。从手机摄影到专业相机，从风光到人像，带你探索光影世界。",
    tags: JSON.stringify(["摄影", "艺术", "设计", "创意", "旅行"]),
    logo: "📷",
    contactInfo: "微信：StarPhoto2024",
    memberCount: 89,
    requirements: "热爱摄影，有无设备均可",
  },
  {
    name: "风华辩论社",
    category: "学术科技",
    description: "以辩会友，锻炼思维与口才。参加校际辩论赛、模拟法庭和演讲比赛。这里有最精彩的思想碰撞和最激烈的观点交锋。",
    tags: JSON.stringify(["辩论", "演讲", "思辨", "口才", "法律"]),
    logo: "🎤",
    contactInfo: "QQ群：987654321",
    memberCount: 67,
    requirements: "善于思考，敢于表达",
  },
  {
    name: "绿芽志愿者协会",
    category: "公益志愿",
    description: "致力于校园及社区公益服务，组织支教、环保行动、敬老院探访等志愿活动。用行动传递温暖，让爱心生根发芽。",
    tags: JSON.stringify(["公益", "志愿", "支教", "环保", "社会服务"]),
    logo: "🌱",
    contactInfo: "微信公众号：绿芽志愿",
    memberCount: 203,
    requirements: "有爱心，愿意奉献时间",
  },
  {
    name: "篮球俱乐部",
    category: "文体艺术",
    description: "热血篮球，青春无限！每周定期训练，参加校际联赛和班级友谊赛。从基础技术到战术配合，专业教练带你提升球技。",
    tags: JSON.stringify(["篮球", "运动", "体育", "团队合作", "健身"]),
    logo: "🏀",
    contactInfo: "微信：Basketball_Club",
    memberCount: 134,
    requirements: "热爱篮球运动，男女不限",
  },
  {
    name: "墨韵书法社",
    category: "文体艺术",
    description: "传承书法艺术，感受笔墨之美。定期书法练习、名家讲座、书法展览，涵盖楷书、行书、隶书、篆书等多种书体。",
    tags: JSON.stringify(["书法", "传统文化", "艺术", "国学", "写作"]),
    logo: "🖌️",
    contactInfo: "QQ群：456789123",
    memberCount: 45,
    requirements: "对书法感兴趣，零基础欢迎",
  },
  {
    name: "创行创业社",
    category: "创新创业",
    description: "孵化创意，点亮梦想！提供创业指导、商业计划培训、投资人对接。参加「互联网+」等创新创业大赛，将你的想法变为现实。",
    tags: JSON.stringify(["创业", "商业", "创新", "领导力", "项目管理"]),
    logo: "🚀",
    contactInfo: "微信公众号：创行未来",
    memberCount: 78,
    requirements: "有创业热情和想法",
  },
  {
    name: "旋律吉他社",
    category: "文体艺术",
    description: "弹唱你的青春！吉他教学从入门到进阶，组织校园弹唱会、音乐节演出。民谣、摇滚、指弹，总有一种风格属于你。",
    tags: JSON.stringify(["吉他", "音乐", "弹唱", "表演", "创作"]),
    logo: "🎸",
    contactInfo: "QQ群：789123456",
    memberCount: 112,
    requirements: "热爱音乐，有无基础均可",
  },
  {
    name: "模拟联合国协会",
    category: "学术科技",
    description: "模拟联合国会议，讨论国际热点议题。培养外交思维、英语能力和全球视野。参加全国及国际模联大会。",
    tags: JSON.stringify(["模联", "国际关系", "英语", "外交", "时事"]),
    logo: "🌍",
    contactInfo: "微信公众号：校园模联",
    memberCount: 56,
    requirements: "对国际事务感兴趣，英语基础良好",
  },
  {
    name: "极限运动社",
    category: "文体艺术",
    description: "滑板、轮滑、攀岩、跑酷！挑战自我极限，体验肾上腺素飙升的快感。专业教练指导，安全装备齐全。",
    tags: JSON.stringify(["极限运动", "滑板", "攀岩", "运动", "冒险"]),
    logo: "🛹",
    contactInfo: "微信：ExtremeSports",
    memberCount: 43,
    requirements: "敢于挑战，注意安全",
  },
  {
    name: "心理健康协会",
    category: "公益志愿",
    description: "关注心灵成长，传播心理健康知识。组织心理沙龙、团体辅导、心理电影赏析等活动，帮助同学们更好地认识自我。",
    tags: JSON.stringify(["心理学", "心理健康", "公益", "沟通", "成长"]),
    logo: "🧠",
    contactInfo: "QQ群：321654987",
    memberCount: 88,
    requirements: "对心理学感兴趣，善于倾听",
  },
  {
    name: "ACG动漫社",
    category: "文体艺术",
    description: "二次元的快乐星球！动漫鉴赏、Cosplay、手绘、同人创作。定期举办漫展、声优大赛和动漫观影会。",
    tags: JSON.stringify(["动漫", "Cosplay", "绘画", "二次元", "创作"]),
    logo: "🎨",
    contactInfo: "QQ群：654987321",
    memberCount: 167,
    requirements: "热爱ACG文化即可",
  },
  // ===== 新增28个 =====
  {
    name: "足球联盟",
    category: "文体艺术",
    description: "绿茵场上的激情碰撞！每周训练、校内联赛、校际友谊赛。从技术训练到战术演练，让你感受团队足球的魅力。",
    tags: JSON.stringify(["足球", "运动", "体育", "团队", "竞技"]),
    logo: "⚽",
    contactInfo: "微信：Football_Union",
    memberCount: 98,
    requirements: "热爱足球，男女队均可报名",
  },
  {
    name: "羽毛球协会",
    category: "文体艺术",
    description: "挥拍之间，尽享运动乐趣。提供专业训练、友谊赛和校际比赛机会。从新手入门到高手对决，总有适合你的场次。",
    tags: JSON.stringify(["羽毛球", "运动", "健身", "竞技", "社交"]),
    logo: "🏸",
    contactInfo: "QQ群：112233445",
    memberCount: 76,
    requirements: "热爱羽毛球运动即可",
  },
  {
    name: "话剧团",
    category: "文体艺术",
    description: "用舞台讲述故事，用表演传递情感。排练经典话剧、原创剧目，每学期至少一场公演。从台前到幕后，戏剧的每个环节都精彩。",
    tags: JSON.stringify(["话剧", "表演", "戏剧", "舞台", "编剧"]),
    logo: "🎭",
    contactInfo: "微信公众号：校园话剧团",
    memberCount: 52,
    requirements: "热爱表演，不限经验",
  },
  {
    name: "街舞社",
    category: "文体艺术",
    description: "Breaking、Popping、Locking、Hip-hop……释放你的舞蹈基因！专业舞者授课，定期battle和公演，校园晚会的常驻嘉宾。",
    tags: JSON.stringify(["街舞", "舞蹈", "嘻哈", "表演", "健身"]),
    logo: "💃",
    contactInfo: "微信：StreetDance_Crew",
    memberCount: 87,
    requirements: "热爱舞蹈，零基础可加入",
  },
  {
    name: "天文爱好者协会",
    category: "学术科技",
    description: "仰望星空，探索宇宙奥秘。组织天文观测、流星雨观赏、天文知识讲座。拥有专业天文望远镜，定期夜间观星活动。",
    tags: JSON.stringify(["天文", "科学", "星空", "物理", "探索"]),
    logo: "🔭",
    contactInfo: "QQ群：556677889",
    memberCount: 38,
    requirements: "对天文宇宙感兴趣",
  },
  {
    name: "数学建模协会",
    category: "学术科技",
    description: "用数学解决现实问题！备战全国大学生数学建模竞赛、美赛MCM/ICM。提供系统培训、组队指导和历年真题训练。",
    tags: JSON.stringify(["数学", "建模", "竞赛", "编程", "数据分析"]),
    logo: "📐",
    contactInfo: "微信：MathModeling2026",
    memberCount: 64,
    requirements: "数学基础良好，有编程能力更佳",
  },
  {
    name: "英语演讲与辩论社",
    category: "学术科技",
    description: "用英语表达观点，用逻辑征服舞台。参加FLTRP杯、21世纪杯等全国英语演讲比赛，以及英语辩论赛。全英文交流环境。",
    tags: JSON.stringify(["英语", "演讲", "辩论", "口语", "国际"]),
    logo: "🗣️",
    contactInfo: "微信公众号：EnglishDebate",
    memberCount: 71,
    requirements: "英语基础较好，敢于开口表达",
  },
  {
    name: "机器人创新工坊",
    category: "学术科技",
    description: "从设计到制造，打造属于你的机器人！参加RoboMaster、机器人大赛等国内顶级赛事。涵盖机械设计、嵌入式开发、视觉算法等领域。",
    tags: JSON.stringify(["机器人", "硬件", "嵌入式", "比赛", "工程"]),
    logo: "🤖",
    contactInfo: "QQ群：998877665",
    memberCount: 49,
    requirements: "对机器人有兴趣，欢迎各专业加入",
  },
  {
    name: "读书会",
    category: "学术科技",
    description: "与书为友，以文会心。每月共读一本好书，举办读书分享会、作家见面会和书评比赛。涵盖文学、哲学、社科等多个领域。",
    tags: JSON.stringify(["阅读", "文学", "哲学", "写作", "思考"]),
    logo: "📚",
    contactInfo: "微信公众号：校园读书会",
    memberCount: 95,
    requirements: "热爱阅读，愿意分享",
  },
  {
    name: "电影协会",
    category: "文体艺术",
    description: "从经典到独立，从好莱坞到艺术片。每周放映+影评讨论，组织微电影拍摄、影评比赛。培养你的电影审美和影像创作能力。",
    tags: JSON.stringify(["电影", "影评", "微电影", "摄影", "导演"]),
    logo: "🎬",
    contactInfo: "微信：FilmClub_Campus",
    memberCount: 83,
    requirements: "热爱电影即可",
  },
  {
    name: "汉服社",
    category: "文体艺术",
    description: "着我华裳，兴我礼仪。研究汉服文化、传统礼仪、古典美学。组织汉服走秀、传统节日活动、古风摄影。",
    tags: JSON.stringify(["汉服", "传统文化", "礼仪", "古风", "历史"]),
    logo: "👘",
    contactInfo: "QQ群：334455667",
    memberCount: 62,
    requirements: "对传统文化有兴趣",
  },
  {
    name: "桌游社",
    category: "文体艺术",
    description: "狼人杀、剧本杀、卡坦岛、三国杀……桌游爱好者的天堂！每周固定开团，不定期举办桌游大赛和新游体验日。",
    tags: JSON.stringify(["桌游", "剧本杀", "社交", "策略", "推理"]),
    logo: "🎲",
    contactInfo: "微信：BoardGame_Club",
    memberCount: 108,
    requirements: "热爱桌游或想认识新朋友",
  },
  {
    name: "瑜伽社",
    category: "文体艺术",
    description: "身心合一，遇见更好的自己。专业瑜伽老师授课，涵盖哈他瑜伽、流瑜伽、阴瑜伽。每周两次练习，帮你缓解学业压力。",
    tags: JSON.stringify(["瑜伽", "健身", "冥想", "养生", "放松"]),
    logo: "🧘",
    contactInfo: "微信：YogaClub_2026",
    memberCount: 73,
    requirements: "不限基础，穿舒适衣服即可",
  },
  {
    name: "跑步爱好者协会",
    category: "文体艺术",
    description: "用脚步丈量校园与城市！组织晨跑、夜跑、半程马拉松训练。从5公里到半马，科学训练帮你不断突破自我。",
    tags: JSON.stringify(["跑步", "马拉松", "运动", "健身", "户外"]),
    logo: "🏃",
    contactInfo: "微信：RunClub",
    memberCount: 145,
    requirements: "热爱跑步，任何速度都欢迎",
  },
  {
    name: "乒乓球社",
    category: "文体艺术",
    description: "国球精神，传承经典。每周训练、内部积分赛、校际对抗赛。从握拍姿势到高级旋转球，系统提升你的乒乓球水平。",
    tags: JSON.stringify(["乒乓球", "运动", "竞技", "体育", "娱乐"]),
    logo: "🏓",
    contactInfo: "QQ群：223344556",
    memberCount: 58,
    requirements: "热爱乒乓球运动",
  },
  {
    name: "合唱团",
    category: "文体艺术",
    description: "用歌声传递力量与美好。排练中外经典合唱曲目，参加校园音乐节、省级合唱比赛。声乐老师专业指导，声部分明。",
    tags: JSON.stringify(["合唱", "音乐", "声乐", "表演", "团队"]),
    logo: "🎵",
    contactInfo: "微信公众号：校园合唱团",
    memberCount: 65,
    requirements: "热爱唱歌，会识谱更佳",
  },
  {
    name: "美食研究社",
    category: "文体艺术",
    description: "探索美食的艺术与科学！烘焙教学、各国料理制作、校园美食测评。每月一次「厨神大赛」，让你的厨艺大放异彩。",
    tags: JSON.stringify(["美食", "烘焙", "料理", "生活", "社交"]),
    logo: "🍳",
    contactInfo: "微信：FoodieClub",
    memberCount: 92,
    requirements: "热爱美食，有无厨艺均可",
  },
  {
    name: "法律援助中心",
    category: "公益志愿",
    description: "以法为盾，为弱势群体提供免费法律咨询。与法学院合作，开展普法宣传、模拟法庭、法律诊所等活动。",
    tags: JSON.stringify(["法律", "公益", "法援", "普法", "志愿"]),
    logo: "⚖️",
    contactInfo: "微信公众号：法援在线",
    memberCount: 41,
    requirements: "法学专业优先，其他专业也欢迎",
  },
  {
    name: "环保行动社",
    category: "公益志愿",
    description: "从校园到社区，践行绿色生活。组织垃圾分类宣传、植树活动、旧物改造市集、环保骑行。让环保成为一种生活方式。",
    tags: JSON.stringify(["环保", "公益", "可持续", "绿色", "志愿"]),
    logo: "♻️",
    contactInfo: "微信：GreenAction2026",
    memberCount: 57,
    requirements: "关注环保，愿意行动",
  },
  {
    name: "支教筑梦团",
    category: "公益志愿",
    description: "用知识点亮希望！每年暑期赴山区支教，平时组织线上辅导。提供教学技能培训、团队建设和安全保障。",
    tags: JSON.stringify(["支教", "公益", "教育", "志愿", "成长"]),
    logo: "📖",
    contactInfo: "QQ群：445566778",
    memberCount: 83,
    requirements: "有耐心有爱心，暑假可外出",
  },
  {
    name: "金融投资俱乐部",
    category: "创新创业",
    description: "从模拟炒股到量化投资，探索金融世界。组织投资分析比赛、金融知识讲座、企业参访。与券商和基金公司建立合作。",
    tags: JSON.stringify(["金融", "投资", "经济", "数据", "商业"]),
    logo: "📈",
    contactInfo: "微信公众号：校园金融圈",
    memberCount: 69,
    requirements: "对金融投资感兴趣",
  },
  {
    name: "新媒体运营社",
    category: "创新创业",
    description: "从0到10万粉丝的实战经验！学习短视频制作、公众号运营、直播带货。运营社团自有账号，积累真实项目经验。",
    tags: JSON.stringify(["新媒体", "短视频", "运营", "内容创作", "直播"]),
    logo: "📱",
    contactInfo: "微信：NewMedia_Club",
    memberCount: 104,
    requirements: "对新媒体有兴趣，有创意",
  },
  {
    name: "电竞社",
    category: "文体艺术",
    description: "LOL、VALORANT、王者荣耀、永劫无间……电竞不只是游戏，更是团队配合与策略较量。组建校队参加CUEA等高校电竞联赛。",
    tags: JSON.stringify(["电竞", "游戏", "团队", "竞技", "策略"]),
    logo: "🎮",
    contactInfo: "QQ群：778899001",
    memberCount: 186,
    requirements: "热爱电竞，有团队意识",
  },
  {
    name: "日语学习社",
    category: "学术科技",
    description: "从五十音到日语能力考！组织日语角、日本文化体验、动漫日语学习。JLPT备考经验分享，日语达人带你入门。",
    tags: JSON.stringify(["日语", "语言", "日本文化", "学习", "动漫"]),
    logo: "🇯🇵",
    contactInfo: "微信：Nihongo_Club",
    memberCount: 72,
    requirements: "对日语和日本文化感兴趣",
  },
  {
    name: "手工创意工坊",
    category: "文体艺术",
    description: "用双手创造美好！涵盖编织、陶艺、皮具、滴胶、纸艺等多种手工。每周一次手工体验课，作品可带走或义卖。",
    tags: JSON.stringify(["手工", "创意", "陶艺", "编织", "DIY"]),
    logo: "✂️",
    contactInfo: "微信：Handcraft_Studio",
    memberCount: 55,
    requirements: "喜欢动手创作，零基础欢迎",
  },
  {
    name: "辩证思维协会",
    category: "学术科技",
    description: "培养批判性思维与逻辑分析能力。组织案例分析、思维导图训练、逻辑谜题挑战赛。让思考成为一种习惯。",
    tags: JSON.stringify(["逻辑", "思维", "批判性思考", "哲学", "分析"]),
    logo: "🧩",
    contactInfo: "QQ群：889900112",
    memberCount: 36,
    requirements: "热爱思考，善于提问",
  },
  {
    name: "国际文化交流协会",
    category: "公益志愿",
    description: "搭建中外文化交流桥梁。组织国际美食节、文化展览、语言交换、留学生联谊。每月一次多元文化之夜。",
    tags: JSON.stringify(["国际", "文化", "交流", "语言", "多元"]),
    logo: "🌐",
    contactInfo: "微信公众号：GlobalCulture",
    memberCount: 63,
    requirements: "对多元文化感兴趣，语言不限",
  },
  {
    name: "游泳社",
    category: "文体艺术",
    description: "从旱鸭子到浪里白条！专业教练教学，涵盖自由泳、蛙泳、蝶泳、仰泳。组织校内游泳比赛和水上趣味运动会。",
    tags: JSON.stringify(["游泳", "运动", "健身", "水上", "竞技"]),
    logo: "🏊",
    contactInfo: "微信：SwimClub_2026",
    memberCount: 48,
    requirements: "不限水平，旱鸭子也欢迎",
  },
  {
    name: "设计师联盟",
    category: "创新创业",
    description: "UI/UX设计、平面设计、品牌视觉……设计师的交流乐园。组织设计比赛、作品展、企业实战项目。Figma、PS技能全覆盖。",
    tags: JSON.stringify(["设计", "UI/UX", "平面", "创意", "Figma"]),
    logo: "🎯",
    contactInfo: "微信：DesignerUnion",
    memberCount: 81,
    requirements: "对设计有兴趣，有无基础均可",
  },
];

async function main() {
  console.log("清空旧数据...");
  await prisma.application.deleteMany();
  await prisma.matchResult.deleteMany();
  await prisma.quizResponse.deleteMany();
  await prisma.student.deleteMany();
  await prisma.club.deleteMany();

  console.log("开始填充社团数据...");
  for (const club of clubs) {
    await prisma.club.create({ data: club });
  }
  console.log(`成功创建 ${clubs.length} 个社团！`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
